apiVersion: v1
kind: Pod
metadata:
  labels:
    run: mynginx
  name: mynginx
spec:
  containers:
  - name: mynginx
    image: nginx
    env:
    - name: configmap-1
      valueFrom:
        configMapKeyRef:
          key: URL
          name: single-config
    - name: configmap-2
      valueFrom:
        configMapKeyRef:
          key: APPSETTING2
          name: multi-config
    envFrom:
    - configMapRef:
        name: multi-config
    volumeMounts:
      - name: config-volume
        mountPath: /etc/config
  volumes:
    - name: config-volume
      configMap:
        name: multi-config
  restartPolicy: Never
