apiVersion: v1
kind: Pod
metadata:
  name: mysecretnginx
spec:
  containers:
  - image: nginx
    name: mysecretnginx
    volumeMounts:
      - name: secret-volume
        readOnly: true
        mountPath: "/etc/secret-volume"
    env:
    - name: DB_PASSWORD
      valueFrom:
        secretKeyRef:
          name: prod-db-secret
          key: DB_PASSWORD
  volumes:
    - name: secret-volume
      secret:
        secretName: prod-db-secret